version: '3.9'

services:
  bank_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Assuming your Go application listens on port 8080
    environment:
      - DB_SOURCE=postgresql://root:mysecretpassword@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]  

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: simple_bank
    ports:
      - "5432:5432"

# sudo docker compose up -d postgres
# sudo docker compose build
# sudo docker compose up bank_api